
title: My Resume
url: 'http://shekharsingh1987.github.io'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6




#Profile information
name: Shekhar Kumar
tagline: Full Stack Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: shekharsingh_1987@yahoo.com
phone: +91 9037243875
website: shekharsingh1987.github.io #do not add http://
linkedin: shekharsingh
github: shekharsingh1987
twitter: '@bulletinbible'

